### ISSUE TITLE
Maybe move to Automattic's repository?

### ISSUE THREAD

**Issue by n8finch** [wordpressenginetracker/wordpressenginetracker.github.io#22]
Why isn't this project in the Automattic repository?

Since this project:
- is stated to be "an Automattic thingamajig"
- uses "WordPress" in the domain (which also assumes that permission was [given from the WP Foundation](https://wordpressfoundation.org/trademark-policy/))
- the domain is pointing to Automattic nameservers

If this is an "official" project, it should be officially in the Automattic repository. Otherwise it could be seen as illegitimate, phishing, etc.

Accompanying screenshots:

![WP_Engine_Tracker](https://github.com/user-attachments/assets/6d596902-055a-452a-a32e-73605469012e)

![Cursor_and_Whois_wordpressenginetracker_com](https://github.com/user-attachments/assets/9e5e4716-1d82-4ded-bce8-bdeae0b03f6c)

**Comment by Neustradamus** [comment]
@n8finch: I have created a ticket to convert this personnal account to an organization, not to move into another organization.
The problem is this WP Engine Tracker personal account, it is not a person:
- https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/issues/26

My ticket must be reopened, it has been not solved.

GitHub Terms of Service:
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements
