### ISSUE TITLE
Remove domains.csv file

### ISSUE THREAD

**Issue by jeffgreco** [wordpressenginetracker/wordpressenginetracker.github.io#28]
Hey jerks,

[This court order](https://storage.courtlistener.com/recap/gov.uscourts.cand.437474/gov.uscourts.cand.437474.64.0.pdf) says knock it off. So knock it off. 

Cheers.

**Comment by nullfekt** [comment]
They have 72 hours and there are only public domain names in the list:

The ruling states the following:
> remove the purported list of WPEngine **customers** contained in the “domains.csv”

Interestingly, it does not state to delete the file or the site. WPE isn't a domain registrar so the domain registrations aren't even their "customers". If they wanted, there is nothing in the ruling preventing the site from being modified to work with a non-public list that still updates `site-count.json`.

The ruling is based on what WPE attested to, which has various technical holes experts can argue in court.

**Comment by jeremyBanks** [comment]
@nullfekt if you’re trying to land them with a Contempt of Court charge, keep talking

**Comment by jonolds** [comment]
@nullfekt lol did anything in that ruling lead you to believe this judge is a secretly a "more shenanigans" appreciator?

**Comment by joshmanders** [comment]
@jeremyBanks I'm sure Matt himself will do enough of that for everyone.

**Comment by nullfekt** [comment]
> @nullfekt if you’re trying to land them with a Contempt of Court charge, keep offering your advice.

It's not advice. Just factual based on the source code and data. They actually went a step further and deleted the file entirely. The site still works because it doesn't rely on the CSV in the order.

**Comment by thaikolja** [comment]
How much pettier can this story become... Matt, just retire! Your image is image is irreparably damaged; there's no coming back from this.

**Comment by nullfekt** [comment]
> Matt, just retire! 

Agreed. He should shutdown .org, go proprietary, and let others do whatever they want with the existing GPL code like always.

**Comment by jonolds** [comment]
he could, but we'd end up in a similar place to where we are right now within a couple of days. the underlying issue is he encouraged people, for years, to build businesses on an open source project that's tied to a specific repo, but misled them about the ownership of the repo. That's fixable, and in that scenario would probably get fixed faster. In short: a judge could remedy his fraud by putting the repo under the control of the foundation, as he's always led people to believe it was anyway. Then it's just a matter of a non-profit chair not acting in accordance with the project's mission. Also fixable by a court.

**Comment by nullfekt** [comment]
> @nullfekt he could, but we'd end up in a similar place to where we are right now within a couple of days.

The day a court rules what a maintainer of a GPL project must do with their code and own infrastructure is the day GPL is dead. There is zero legal basis to force .org or any open source project to provide their services free forever. The only thing that is guaranteed free for ever is the source code itself. That is how GPL works. 

I don't expect non-technical lawyers or judges to understand any of this in a preliminary hearing, nor do I fault them. It's not like they actually read or understood the source code in this repo if they requested something useless like the "customers" from the domains.csv to be removed. 

The larger issues IMO are the clear trademark stuffing WP Engine engaged with renaming all their plans to specifically include the trademarks, all shortly after receiving an initial term sheet in May 2024. I'd imagine this will all be argued in court once it gets there instead of the judge only seeing the picture that's been painted by WP Engine.

**Comment by nathanielks** [comment]
@nullfekt I'd encourage you to lookup "promissory estoppel" and how that applies in this circumstance. It'll help you understand why the preliminary injunction was granted.

> with their code and own infrastructure

Of note, no decisions were made concerning the _code_ of WordPress, so GPL means nothing in this conversation. GPL has no effect on the services that WordPress as software rely upon, _that are hard-coded into the software itself._

**Comment by jonolds** [comment]
none of these issues have anything to do with GPL. GPL doesn't give you any extra protections from the normal laws that govern business relationship. It's not legal (or fair) to get people to build business around a project that you've led them to believe is governed by the bylaws of a non-profit, only to tell them many years later that actually the infrastructure is privately owned and now we're changing the rules. That's the fraudulent part. It has nothing to do with GPL.

**Comment by nullfekt** [comment]
> I'd encourage you to lookup "promissory estoppel"
What promises were ever made to WP Engine other than what's in the GPL license?

> GPL means nothing in this conversation.

In this injunction ruling it doesn't, however, I am specifically speaking of the bigger picture and potential end game result of a total shutdown. Others can foot the bill to maintain and contribute to GPL code they want to still use due to WP Engine's retaliatory lawsuit for their trademark violations. 

> GPL has no effect on the services that WordPress as software rely upon, that are hard-coded into the software itself.

Any "hard-coded" values can be changed by anyone. That is the nature of open source. What's next, lawsuits demanding nulled plugins be hosted on .org, claiming it's the only way to securely update them because users are dumb?

> It's not legal (or fair) to get people to build businesses around a project that you've led them to believe is governed by the bylaws of a non-profit

Life isn't fair. It would be foolish to believe any open source project has any promises other than what's spelled out in the license. WP Engine's declarations as to who owns and controls what amounts to "we didn't know."

**Comment by jonolds** [comment]
lol. on the last point: again, nothing to do with open source. Open source provides no additional protections. Also love that you responded to the aside in parentheses (fair), instead of the actual argument, "legal". Are you confused about how language works, or are you just operating in bad faith? Nevermind, I don't really care. have fun defending a creep!

**Comment by nathanielks** [comment]
> What promises were ever made to WP Engine other than what's in the GPL license?

Again, look up what promissory estoppel means. From Google:

> Promissory estoppel is a legal doctrine that allows a plaintiff to recover damages from a defendant even when there is no formal contract. It applies when the defendant made a promise that the plaintiff reasonably relied on, and the plaintiff suffered a detriment as a result. 

> The requirements for promissory estoppel are:
> - The defendant made a clear and unambiguous promise 
> - The plaintiff relied on the promise 
> - The plaintiff's reliance was reasonable and foreseeable 
> - The plaintiff suffered an injury due to relying on the promise 
> - The only way the plaintiff can be compensated is if the defendant fulfills the promise 

Referring back to hard coded values, dot org's update servers are hard-coded into the WordPress software itself. Having access to the update servers is the "promise that the plaintiff reasonably relied on," given there's no contracts or requirements to use the update servers. GPL has nothing to do with this; Matt _choosing_ to offer the _service_ of the update servers has nothing to do with the GPL software license.

In all seriousness, go back and read the text of the preliminary injunction. It's written well and the judge clearly outlines the reasoning and justification for granting the order. Pages 1-28 are the facts leading up to the order, and 28 on are the justification.

---

Re: it's open source, anyone can change it or modify it. I'm assuming you've never tried contributing to WordPress Core. That's where sanity goes to die. 

I'll leave you with that.

**Comment by nullfekt** [comment]
> nothing to do with open source

The entire case is about open source and stemmed from protecting the marks owned by the WordPress Foundation from dilution, which Automattic has the rights to exploit and sublicense.

> Again, look up what promissory estoppel means. From Google:

Not interested in being a Google or YouTube lawyer. The injunction ruling has zero to do with their promissory estoppel claim. It is solely to preserve the status quo ante litem pending a determination of the action on the merits.

> Having access to the update servers is the "promise that the plaintiff reasonably relied on"

This is not promised anywhere in the software or GPL license. They are conflating the freedom of the source code with free services others provide, which are kindly integrated into WordPress Core, and are not necessary for WordPress to function. 

>  I'm assuming you've never tried contributing to WordPress Core

You don't need to contribute to Core to change how the software works. That is the freedom that GPL promises. Have you never forked a project and cherry picked only what you wanted from upstream and gave PRs back as a courtesy? You can literally run your own fork to only change how plugins update and leech off upstream. I heard WP Engine was capable of doing it in a couple days or something. I guess it took them years of acquiring other's code to realize it was possible. Maybe they will make some contributions now that they've got it all figured out? 

Since you bring up contributing to Core, it's important to understand many core contributors have left the project already. Automattic is the largest contributor based on Five for the Future pledges. Does anyone genuinely think they will continue to contribute if they are legally punished for attempting to protect their trademarks from FOSS leeches? 

Real talk, is there a class-action I can join to sue Microsoft because I can't update Windows 95? I was totally relying on being able to update it forever. Some jerk keeps sending me a ping of death during the middle of my conversations on IRC and it's ruining my pitiful life.

**Comment by GabrielRavier** [comment]
@nullfekt It may be that the order does not technically make "a determination of the action on the merits" but I think such wording as:

> the Court finds that WPEngine is likely to succeed on the merits of its intentional interference with contractual relations claim. Defendants' arguments in opposition do not compel a different conclusion.

(from the preliminary injunction) should make it clear what determination the court is likely to make in this regard.

Also:

> This is not promised anywhere in the software or GPL license. They are conflating the freedom of the source code with free services others provide, which are kindly integrated into WordPress Core, and are not necessary for WordPress to function.

The GPL license literally has absolutely nothing whatsoever to do with the promise in question. This lawsuit would be going the exact same way if WordPress had been proprietary software.

**Comment by nullfekt** [comment]
> should make it clear what determination the court is likely to make in this regard

The ruling has nothing to do with what the outcome of a case may be. It's strictly to return things to status quo until trial where all evidence is heard and to prevent further fuckery until then. 

> The GPL license literally has absolutely nothing whatsoever to do with the promise in question.

Do tell the promise in question.

The license is the only legally binding contract. WP Engine chose to build a business around GPL software, which has no warranty or liability for any damages - placing all risks, repairs, and costs on them. Nearly their entire complaint and anti-trust claims are based on the promises of WordPress being free, while claiming it's no longer free, costing money, and stifling competition. 

They are citing the promises of GPL while conflating it with trademark licensing. The freedom promised under WordPress is freedom to do what you want with the source code, not freedom to infringe trademarks. Their access to WordPress source code has never stopped being free nor been blocked, despite WP Engine charging customers to use WordPress and creating commercial plugins that update without .org. They have proven they can modify the software to compete however they wish. 

Previous courts have also ruled GPL can't violate anti-trust laws due to the very nature of the license. It's impossible to create "monopolistic pricing" when the software is free of charge for anyone to take, modify, and compete. The judge likely hasn't even read the license yet and certainly has not heard any counterclaims or arguments on the true basis of WP Engine filing suit first. That of course is for their blatant trademark infringement and not wanting to pay commercial trademark licensing after including the defendant's marks in their product and service names (IE: "Core WordPress") since at least May 2024.

That use has never been allowed, not even before the WordPress Foundation modified the policy to diss WP Engine. Their use also fails the 3-prong test for the nominative fair use they claim. Prior to adding the marks to all of their product names around the same time as receiving the first term sheet, they sold the same products for years without including the marks, proving they are readily identified without.

That infringement and other instances was clearly for trademark stuffing and unfair competition based on the brand reputation the marks have built. Any licensee such as Newfold should join a counterclaim for injuries since they are indirectly mentioned in the complaint for having paid a license, which WP Engine's lawyers argue is not necessary.

**Comment by GabrielRavier** [comment]
> The ruling has nothing to do with what the outcome of a case may be. It's strictly to return things to status quo until trial where all evidence is heard and to prevent further fuckery until then.

The ruling is not on the outcome of the case, yes. However, I think you will find that cases in which the court explicitly stated at the preliminary injunction stage that "the Court finds that [plaintiff] is likely to succeed on the merits of [their claim]. Defendants' arguments in opposition do not compel a different conclusion." were far more likely to end in favor of the plaintiff than in cases where the court did not do so.

>  The judge likely hasn't even read the license yet

This seems to contradict your earlier claim that the rulings being made in this case are caused by the GPL.

>  [The judge] certainly has not heard any counterclaims or arguments on the true basis of WP Engine filing suit first

What part of "Defendants' arguments in opposition do not compel a different conclusion" makes you think the judge hasn't heard arguments from the defendants ?

> They are citing the promises of GPL while conflating it with trademark licensing.

I would quite appreciate it if you could give a source on when/where exactly WPEngine has claimed that the GPL gives them trademark licensing. As far as I've been able to see, they have not done so, and their trademark claims are entirely unrelated to the GPL (I've read the complaint and those claims seem to be primarily based around Mullenweg lying about who has control of the trademark and under what terms people can make use of it).
