### ISSUE TITLE
Track actual sites, not domains

### ISSUE THREAD

**Issue by f3bruary** [wordpressenginetracker/wordpressenginetracker.github.io#3]
The summary of this project is:

> The purpose of this site is to track how many sites have left WP Engine

Based on the very first entries in the list I found 16 domains all pointing to 1 site. That makes the counter misleading.

Either the summary should be updated so it says domains instead of sites, or the list needs to be filtered down to actual sites, and  not all the domains that point to one.

**Comment by stephcathoh** [comment]
It's possible some folks have left WordPress as well, so saying sites have left WP Engine doesn't necessarily mean they've gone to another web host that supports WordPress. This is a really tacky endeavor. I am not impressed at all.

**Comment by DanielRuf** [comment]
Also the check, if a domain is hosted by WPE, is quite amateurish.

https://github.com/wordpressenginetracker/wordpressenginetracker.github.io/blob/trunk/index.js#L118

* missing dot at beginning for some
* only checks subdomains

I'm not sure what the goal of this website is and what Matt tries to achieve. But the community is getting increasingly annoyed of such unprofessional behavior of Matt and in the security community some also think about dropping 0days for WordPress and related plugins / themes due to this whole situation.

The feedback under the tweet from the official WordPress account and in the reddit community shows, what most of us think.

The whole situation hurts everyone more than needed.

**Comment by f3bruary** [comment]
> in the security community some also think about dropping 0days for WordPress...

That would punish the users and the theme/plugin authors more than WP/MM. It would be equal to MM blocking WPE's access to the plugin repository.

I don't want to go out of the scope of this ticket, which simply points to the incorrectness of the counter, but if you want to punish the responsible it needs to be a loss of market share. The best thing people can do is stop using WP. Stop developing themes and plugins, and stop offering support and maintenance.

It's the developers that built WP to what it is now and are responsible for its popularity (ignoring the block editor for the sake of the argument and avoid PTSD/trauma/flashbacks/migraines).

The community has the power to destroy it as well by shifting to another platform. Many already have.

In time, WP would become the Yahoo of CMS platforms.

**Comment by mathieuwa** [comment]
More wasted time, more useless action made by Matt. The community being annoyed is an euphemism. Matt told automattic was short staffed and yet it seems some staff have time to waste. Matt is deserving what is coming and I really hope a slap from justice will wake him up.

**Comment by DanielRuf** [comment]
> That would punish the users and the theme/plugin authors more than WP/MM.

I think they have the feeling, that Automattic is not a responsible party anymore for a vulnerability reporting process. Especially since Automattic used the reason with a vulnerability to takeover the ACF plugin.

**Comment by DanielRuf** [comment]
> The community has the power to destroy it as well

Totally agree. There are more ways, but it seems Matt is deliberately ignoring this risk and makes everyone more frustrated.

**Comment by pwillia7** [comment]
Ick

**Comment by taserak** [comment]
Ok, what i learned today that Wordpress phones home and that this site exists. 
I think I'm never using Wordpress again for any site in the future.  

Gutenberg is still terrible. Its sad that the ancient editor is so much easier for regular users to understand and use. 

WPengine's Advanced Custom Fields is almost completely necessary to easily and quickly customize, edit, and control a site. 
wrangling WP to just access its own built-in features can be such a clusterfuck.

You are the pettiest person I've heard about.
You are probably just mad a company made a lot of money just by focusing on fixing your shortcomings.

**Comment by yCodeTech** [comment]
> It's the developers that built WP to what it is now and are responsible for its popularity

Agreed. So does anyone wanna fork WordPress into a separate entity? Matt literally said he welcomes forks. So we can just make our own company on the backbone of wp open source code. We will naturally gain popularity and move the wp community over to the new and improved company.

**Comment by wordpressenginetracker** [comment]
> Based on the very first entries in the list I found 16 domains all pointing to 1 site. That makes the counter misleading.

Thanks for the report @f3bruary. We had been properly removing the redirected sites from the count of moved sites, but had only removed about 100k of the 250k redirected domains from the export. We're now properly both removing redirected domains and adding the domains that are being redirected to when appropriate. The current export has been updated to fix this and the site design is now displaying our count of the number of sites and how it has changed: https://wordpressenginetracker.com/.

Our total count and domain list is still a bit higher than what Builtwith has: https://trends.builtwith.com/websitelist/WP-Engine

> It's possible some folks have left WordPress as well, so saying sites have left WP Engine doesn't necessarily mean they've gone to another web host that supports WordPress.

@stephcathoh based on our data about 2-3% of the moved sites have been confirmed to have moved off of WordPress (squarespace, wix, drupal, etc).

Closing since the original issue is fixed.
