### ISSUE TITLE
Usage of trademarked term "wordpress" in domain not permissible

### ISSUE THREAD

**Issue by davidwolfpaw** [wordpressenginetracker/wordpressenginetracker.github.io#6]
The WordPress trademark policy makes it clear that using the term "wordpress" as part of a domain name is not permissible.

> Permission from the WordPress Foundation is required to use the WordPress or WordCamp name or logo as part of any project, product, service, **domain name**, or company name.

As part of the trademark policy, found at [https://wordpressfoundation.org/trademark-policy/](https://wordpressfoundation.org/trademark-policy/), There are three criteria laid out for usage of the trademark:

- The primary purpose of your project is to promote the spread and improvement of the WordPress software.
- Your project is non-commercial in nature (it can make money to cover its costs or contribute to non-profit entities, but it cannot be run as a for-profit project or business).
- Your project neither promotes nor is associated with entities that currently fail to comply with the GPL license under which WordPress is distributed.

It can be argued that all three of these checks fail, and the wording on the trademark policy reads as if all three need to be met.

Even if these three criteria are somehow met via this site, the following information is in the policy (bolding for emphasis my own):

> If your project meets these criteria, you will be permitted to use the WordPress name and logo to promote your project in any way you see fit **with one exception: Please do not use WordPress or WordCamp as part of a domain name**.

> All other WordPress-related businesses or projects can use the WordPress name and logo to refer to and explain their services, but they cannot use them as part of a product, project, service, **domain name**, or company name and they cannot use them in any way that suggests an affiliation with or endorsement by the WordPress Foundation or the WordPress open source project.

> **Under no circumstances is it permitted to use WordPress or WordCamp as part of a domain name or top-level domain name**.

The URL for this website, [https://wordpressenginetracker.com/](wordpressenginetracker.com) very clearly violates these guidelines.

**Comment by SpikeViper** [comment]
i am sure the rules will be applied very evenly and that this stunt won't look terrible in the lawsuit

**Comment by pwillia7** [comment]
Petty Kings have petty kingdoms

**Comment by jprjr** [comment]
The domain is pretty confusing as well. "WordPress Engine" isn't a thing, the company being tracked isn't named "WordPress Engine" - it's named "WP Engine". It would make a lot more sense to use https://wpenginetracker.com

**Comment by sc0ttkclark** [comment]
Is this commercial use by Automattic? It seems like a marketing page for Pressable.

**Comment by m** [comment]
This is covered by Automattic's commercial license for the WordPress trademark.

**Comment by davidwolfpaw** [comment]
> This is covered by Automattic's commercial license for the WordPress trademark.

How is this covered? 

At the very least there is confirmation here that this is indeed officially sanctioned by you and Automattic as a company.

I assume that @wpengine would already be aware of that, but it's useful to have clarification.

**Comment by bhowe** [comment]
After all he does your really think he cares about breaking rules or hurting people. Your wasting your time

**Comment by sc0ttkclark** [comment]
It's okay, this site exists for commercial purposes. We can close this ticket since they are allowed to have commercial domains with wordpress in it.

But, this site exists for commercial purposes. So remember that key fact.

**Comment by robin-scott** [comment]
> This is covered by Automattic's commercial license for the WordPress trademark.

@m do you have permission from the WordPress Foundation to do this though?

The wording on this is about:

`Please do not use WordPress or WordCamp as part of a domain name. Examples of projects in this category are officially recognized WordCamps or international WordPress communities that are dedicated to the translation and distribution of WordPress in their respective countries.`

This is explicitly not that.

The issue here is NOT commercial use, it's use of the word WordPress in the domain name. You'd need to get permission from the WordPress Foundation. Do you have that? I'm aware this would probably involve asking yourself a question, but there are other board members. They probably agree. But the right to commercially exploit the TM is a different thing.

**Comment by nullfekt** [comment]
@robin-scott Automattic was granted permission long ago to an exclusive, fully-paid, royalty-free, perpetual, irrevocable, worldwide, sublicensable right and license to use and otherwise exploit the trademarks. The trademark policy doesn't apply to them: https://assignments.uspto.gov/assignments/assignment-tm-4233-0808.pdf

**Comment by robin-scott** [comment]
> @robin-scott Automattic was granted permission long ago to an exclusive, fully-paid, royalty-free, perpetual, irrevocable, worldwide, sublicensable right and license to use and otherwise exploit the trademarks. The trademark policy doesn't apply to them: https://assignments.uspto.gov/assignments/assignment-tm-4233-0808.pdf

Not that long ago, in the scheme of things, because I certainly remember it happening. 

My point is not about license, it is about permission. The Foundation says you need permission to make a domain containing the name WordPress. It would make sense to identify all instances of permitted usages of domains containing the word, since this list is probably fewer than 10 domains.

When the Foundation at the centre of a project says "Please do not..." [do the thing that has just been done], it is right that this question should be raised.

**Comment by nullfekt** [comment]
That assignment was in 2010. There is no additional permission needed. It's like arguing how wordpress.com exists. The license lets them exploit the trademarks however they wish, including registering domain names.

**Comment by jprjr** [comment]
I don't think any argument based on trademark law is going to go anywhere. 

If you look at that agreement from a few comments up, guess whose signature is on the agreement representing the WordPress Foundation? Why it's Matt, of course.

It's pretty obvious that Matt is WordPress. He doesn't seem to care what the community thinks (they've been very vocal), he's intentionally surrounded himself with sycophants by buying out any Automattic employees that disagree with him. 

The best thing for WordPress is to get Matt out.

**Comment by nullfekt** [comment]
> If you look at that agreement from a few comments up, guess whose signature is on the agreement representing the WordPress Foundation? Why it's Matt, of course.

That should be expected because he is the founder of the WordPress Foundation. Who else would sign it?

I'm more surprised that WP Engine and others are clueless about the history of WordPress and thought anyone else was running it. So far their only defense is they don't need any trademark license, while profiting from it commercially in their plan names alone.

**Comment by davidwolfpaw** [comment]
> I'm more surprised that WP Engine and others are clueless about the history of WordPress

We are not clueless about the history. We are just not of the opinion that, "just because he did it, means that he should be able to do it."

I would rather express support and work toward seeing the things that I want to see in the world, as opposed to just shrugging and saying, "well, nothing can be done, so why say anything?"
